FROM ghcr.io/allenai/conda:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
  && apt-get install -y default-jre \
  && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

CMD []
ENTRYPOINT ["/./net/nfs.cirrascale/aristo/harsht/elasticsearch-7.10.2/bin/elasticsearch"]
